- name: Elastic events
  hosts: localhost
  sources:
    - cloin.eda.elastic:
        elastic_host: 10.8.230.25
        elastic_port: 9200
        elastic_username: admin
        elastic_password: P@ssw0rd
        elastic_index_pattern: .ds-logs-system.syslog-default-2023.10.09-000001
        query: |
          term:
            AIRLINE.keyword: WN
        interval: 5
  rules:
    - name: Debug event
      condition: event.ecs is defined and event.nginx.log_level == "error"
      action:
        debug:
