- name: Elastic events
  hosts: localhost
  sources:
    - cloin.eda.elastic:
        elastic_host: 10.8.230.25
        elastic_port: 9200
        elastic_username: admin
        elastic_password: P@ssw0rd
        elastic_index_pattern: heartbeat-*
        query: |
          {
            "bool": {
              "must": [
                { "term": { "monitor.id": "httpd-monitor" }},
                {
                  "range": {
                    "@timestamp": {
                      "gte": "now-5s",
                      "lt": "now"
                    }
                  }
                }
              ]
            }
          }
        interval: 30  # Check every 1 minute
  rules:
    - name: Heartbeat monitor check
      condition: event.ecs is defined and event.state.status == "down"
      action:
        run_job_template:
          name: "Restart HTTPd"
          organization: Default
