- name: Elastic events
  hosts: localhost
  sources:
    - cloin.eda.elastic:
        elastic_host: 10.8.230.25
        elastic_port: 9200
        elastic_username: admin
        elastic_password: P@ssw0rd
        elastic_index_pattern: heartbeat-*
        query: |
          term:
            monitor.id.keyword: "httpd-monitor"
        interval: 15
  rules:
    - name: Heartbeat monitor check
      condition: event.monitor.status == "down"
      action:
        debug:
