- name: Elastic events
  hosts: localhost
  sources:
    - cloin.eda.elastic:
        elastic_host: 10.8.230.25
        elastic_port: 9200
        elastic_username: admin
        elastic_password: P@ssw0rd
        elastic_index_pattern: alert-for-ansible
        query: |
          term:
            host.ip.keyword: 10.8.230.25,fe80::20c:29ff:fe40:55aa
        interval: 5
  rules:
    - name: Debug event
      condition: 
        script: |
          def cpuUsage = Double.parseDouble(doc['_source']['cpu.usage'].value.replaceAll('%', ''));
          return cpuUsage > 3.0;
      action:
        debug:
